/**
 * Author : Faruq
 * List Constant
 */

module.exports = {
    DEVICE_ACTIVE:1,
    DEVICE_NONACTIVE:0,
    NORMAL_CONDITION:1,
    ABNORMAL_CONDITION:0,
    HEARTRATE_LOWER_LIMIT:60,
    HEARTRATE_UPPER_LIMIT:100,
    OXYGEN_lOWER_LIMIT:95,
    OXYGEN_UPPER_LIMIT:100,
    TEMPERATURE_LOWER_LIMIT:36,
    TEMPERATURE_UPPER_LIMIT:38,
    GSR_lOWER_LIMIT:25,
    GSR_UPPER_LIMIT:29,
    ECG_lOWER_LIMIT:0.6,
    ECG_UPPER_LIMIT:1.2,
}